services:
  - type: web
    name: millet-food-service
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: SESSION_SECRET
        fromSecret: SESSION_SECRET
      - key: RAZORPAY_KEY_ID
        fromSecret: RAZORPAY_KEY_ID
      - key: RAZORPAY_KEY_SECRET
        fromSecret: RAZORPAY_KEY_SECRET
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        value: AIzaSyAnwH0jPc54BR-sdRBybXkwIo5QjjGceSI
      - key: VITE_GOOGLE_MAPS_API_KEY
        value: AIzaSyAnwH0jPc54BR-sdRBybXkwIo5QjjGceSI
      - key: FAST2SMS_API_KEY
        value: ZqmW2sE3CUbwLTH4c0XDQMJk169zlNRonAvYP7tGyhpgOjaV8ujIYLf1CMOBQaKR93qdcE6ySmTZrNW5
      - key: FAST2SMS_SENDER_ID
        value: FSTSMS
      - key: VITE_API_BASE_URL
        value: https://millet-food-service.onrender.com
      - key: FRONTEND_URL
        value: https://millet-food-service.onrender.com
      - key: RENDER_SERVICE_NAME
        value: millet-food-service