services:
  - type: web
    name: millet-food-service
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
      - key: VITE_API_BASE_URL
        value: https://millet-food-service.onrender.com
      - key: FRONTEND_URL
        value: https://millet-food-service.onrender.com
      - key: RENDER_SERVICE_NAME
        value: millet-food-service