// This file contains the meal data types for MongoDB storage
// Imported by mongoStorage.ts and seed.ts

export interface MealDataItem {
  id?: number;
  name: string;
  description: string;
  price: number;
  imageUrl?: string;
  mealType: string;
  category?: string;
  dietaryPreference: string;
  ingredients?: string[];
  nutritionalInfo?: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
  };
  available?: boolean;
  popular?: boolean;
  spiceLevel?: number;
  preparationTime?: number;
  basePrice?: number;
  defaultCurryOption?: string;
}

// 38 Millet-based meal options for millet food service platform
export const milletMeals: MealDataItem[] = [
  {
    id: 1,
    name: "Pearl Millet Khichdi",
    description: "Nutritious khichdi made with pearl millet, moong dal, and aromatic spices",
    price: 180,
    mealType: "lunch",
    category: "Main Course",
    dietaryPreference: "vegetarian",
    ingredients: ["Pearl Millet", "Moong Dal", "Turmeric", "Cumin", "Ginger"],
    nutritionalInfo: { calories: 320, protein: 12, carbs: 58, fat: 6, fiber: 8 },
    popular: true,
    spiceLevel: 2,
    preparationTime: 30
  },
  {
    id: 2,
    name: "Finger Millet Roti",
    description: "Healthy flatbread made from finger millet flour with ghee",
    price: 120,
    mealType: "lunch",
    category: "Bread",
    dietaryPreference: "vegetarian",
    ingredients: ["Finger Millet Flour", "Water", "Salt", "Ghee"],
    nutritionalInfo: { calories: 210, protein: 8, carbs: 35, fat: 5, fiber: 6 },
    popular: true,
    spiceLevel: 1,
    preparationTime: 20
  },
  {
    id: 3,
    name: "Foxtail Millet Upma",
    description: "South Indian breakfast dish with foxtail millet and vegetables",
    price: 160,
    mealType: "breakfast",
    category: "Breakfast",
    dietaryPreference: "vegetarian",
    ingredients: ["Foxtail Millet", "Onions", "Carrots", "Green Peas", "Curry Leaves"],
    nutritionalInfo: { calories: 280, protein: 9, carbs: 52, fat: 4, fiber: 7 },
    popular: false,
    spiceLevel: 2,
    preparationTime: 25
  },
  {
    id: 4,
    name: "Barnyard Millet Pulao",
    description: "Fragrant pulao made with barnyard millet and mixed vegetables",
    price: 200,
    mealType: "lunch",
    category: "Rice Dishes",
    dietaryPreference: "vegetarian",
    ingredients: ["Barnyard Millet", "Basmati Rice", "Mixed Vegetables", "Whole Spices"],
    nutritionalInfo: { calories: 340, protein: 10, carbs: 62, fat: 7, fiber: 8 },
    popular: true,
    spiceLevel: 2,
    preparationTime: 35
  },
  {
    id: 5,
    name: "Little Millet Idli",
    description: "Steamed idlis made from little millet and urad dal batter",
    price: 140,
    mealType: "breakfast",
    category: "Breakfast",
    dietaryPreference: "vegetarian",
    ingredients: ["Little Millet", "Urad Dal", "Fenugreek Seeds", "Salt"],
    nutritionalInfo: { calories: 250, protein: 11, carbs: 45, fat: 3, fiber: 6 },
    popular: true,
    spiceLevel: 1,
    preparationTime: 45
  },
  {
    id: 6,
    name: "Pearl Millet Porridge",
    description: "Creamy breakfast porridge with pearl millet, milk, and nuts",
    price: 150,
    mealType: "breakfast",
    category: "Porridge",
    dietaryPreference: "vegetarian",
    ingredients: ["Pearl Millet", "Milk", "Almonds", "Dates", "Cardamom"],
    nutritionalInfo: { calories: 290, protein: 12, carbs: 48, fat: 8, fiber: 7 },
    popular: false,
    spiceLevel: 0,
    preparationTime: 25
  },
  {
    id: 7,
    name: "Finger Millet Dosa",
    description: "Crispy dosa made from finger millet and rice batter",
    price: 130,
    mealType: "breakfast",
    category: "Breakfast",
    dietaryPreference: "vegetarian",
    ingredients: ["Finger Millet", "Rice", "Urad Dal", "Fenugreek Seeds"],
    nutritionalInfo: { calories: 240, protein: 9, carbs: 42, fat: 4, fiber: 6 },
    popular: true,
    spiceLevel: 1,
    preparationTime: 20
  },
  {
    id: 8,
    name: "Kodo Millet Biryani",
    description: "Aromatic biryani with kodo millet, vegetables, and fragrant spices",
    price: 220,
    mealType: "lunch",
    category: "Rice Dishes",
    dietaryPreference: "vegetarian",
    ingredients: ["Kodo Millet", "Mixed Vegetables", "Mint", "Saffron", "Biryani Spices"],
    nutritionalInfo: { calories: 380, protein: 11, carbs: 68, fat: 8, fiber: 9 },
    popular: true,
    spiceLevel: 3,
    preparationTime: 50
  },
  {
    id: 9,
    name: "Proso Millet Soup",
    description: "Nutritious soup with proso millet, vegetables, and herbs",
    price: 120,
    mealType: "dinner",
    category: "Soup",
    dietaryPreference: "vegetarian",
    ingredients: ["Proso Millet", "Tomatoes", "Carrots", "Spinach", "Herbs"],
    nutritionalInfo: { calories: 180, protein: 7, carbs: 32, fat: 3, fiber: 5 },
    popular: false,
    spiceLevel: 1,
    preparationTime: 30
  },
  {
    id: 10,
    name: "Barnyard Millet Cutlet",
    description: "Crispy cutlets made with barnyard millet and vegetables",
    price: 140,
    mealType: "dinner",
    category: "Snacks",
    dietaryPreference: "vegetarian",
    ingredients: ["Barnyard Millet", "Potatoes", "Green Beans", "Bread Crumbs"],
    nutritionalInfo: { calories: 260, protein: 8, carbs: 38, fat: 9, fiber: 6 },
    popular: false,
    spiceLevel: 2,
    preparationTime: 35
  },
  {
    id: 11,
    name: "Pearl Millet Pancakes",
    description: "Fluffy pancakes made with pearl millet flour and topped with honey",
    price: 170,
    mealType: "breakfast",
    category: "Breakfast",
    dietaryPreference: "vegetarian",
    ingredients: ["Pearl Millet Flour", "Eggs", "Milk", "Honey", "Baking Powder"],
    nutritionalInfo: { calories: 310, protein: 10, carbs: 45, fat: 11, fiber: 6 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 20
  },
  {
    id: 12,
    name: "Finger Millet Cookies",
    description: "Healthy cookies made with finger millet flour and jaggery",
    price: 100,
    mealType: "dinner",
    category: "Dessert",
    dietaryPreference: "vegetarian",
    ingredients: ["Finger Millet Flour", "Jaggery", "Ghee", "Cardamom", "Almonds"],
    nutritionalInfo: { calories: 220, protein: 6, carbs: 32, fat: 8, fiber: 4 },
    popular: false,
    spiceLevel: 0,
    preparationTime: 30
  },
  {
    id: 13,
    name: "Foxtail Millet Salad",
    description: "Fresh salad with cooked foxtail millet, vegetables, and herbs",
    price: 150,
    mealType: "lunch",
    category: "Salad",
    dietaryPreference: "vegetarian",
    ingredients: ["Foxtail Millet", "Cucumber", "Tomatoes", "Mint", "Lemon"],
    nutritionalInfo: { calories: 200, protein: 7, carbs: 35, fat: 4, fiber: 6 },
    popular: false,
    spiceLevel: 1,
    preparationTime: 15
  },
  {
    id: 14,
    name: "Kodo Millet Laddu",
    description: "Traditional sweet laddu made with kodo millet and coconut",
    price: 90,
    mealType: "dinner",
    category: "Dessert",
    dietaryPreference: "vegetarian",
    ingredients: ["Kodo Millet", "Coconut", "Jaggery", "Cardamom", "Nuts"],
    nutritionalInfo: { calories: 180, protein: 4, carbs: 28, fat: 6, fiber: 3 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 25
  },
  {
    id: 15,
    name: "Little Millet Curry",
    description: "Spicy curry with little millet and mixed vegetables",
    price: 190,
    mealType: "lunch",
    category: "Curry",
    dietaryPreference: "vegetarian",
    ingredients: ["Little Millet", "Mixed Vegetables", "Coconut Milk", "Curry Spices"],
    nutritionalInfo: { calories: 320, protein: 9, carbs: 55, fat: 8, fiber: 7 },
    popular: false,
    spiceLevel: 3,
    preparationTime: 40
  },
  {
    id: 16,
    name: "Pearl Millet Bread",
    description: "Nutritious bread made with pearl millet flour",
    price: 80,
    mealType: "breakfast",
    category: "Bread",
    dietaryPreference: "vegetarian",
    ingredients: ["Pearl Millet Flour", "Yeast", "Olive Oil", "Salt", "Water"],
    nutritionalInfo: { calories: 160, protein: 6, carbs: 28, fat: 4, fiber: 5 },
    popular: false,
    spiceLevel: 0,
    preparationTime: 60
  },
  {
    id: 17,
    name: "Barnyard Millet Risotto",
    description: "Creamy risotto made with barnyard millet and mushrooms",
    price: 240,
    mealType: "dinner",
    category: "Main Course",
    dietaryPreference: "vegetarian",
    ingredients: ["Barnyard Millet", "Mushrooms", "Vegetable Stock", "Parmesan", "Wine"],
    nutritionalInfo: { calories: 350, protein: 12, carbs: 58, fat: 9, fiber: 6 },
    popular: true,
    spiceLevel: 1,
    preparationTime: 45
  },
  {
    id: 18,
    name: "Proso Millet Stir Fry",
    description: "Quick stir fry with proso millet and colorful vegetables",
    price: 160,
    mealType: "lunch",
    category: "Stir Fry",
    dietaryPreference: "vegetarian",
    ingredients: ["Proso Millet", "Bell Peppers", "Broccoli", "Soy Sauce", "Ginger"],
    nutritionalInfo: { calories: 250, protein: 8, carbs: 42, fat: 6, fiber: 6 },
    popular: false,
    spiceLevel: 2,
    preparationTime: 20
  },
  {
    id: 19,
    name: "Finger Millet Smoothie",
    description: "Nutritious smoothie with finger millet, banana, and yogurt",
    price: 120,
    mealType: "breakfast",
    category: "Beverages",
    dietaryPreference: "vegetarian",
    ingredients: ["Finger Millet Flour", "Banana", "Yogurt", "Honey", "Milk"],
    nutritionalInfo: { calories: 240, protein: 10, carbs: 38, fat: 6, fiber: 5 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 10
  },
  {
    id: 20,
    name: "Foxtail Millet Pasta",
    description: "Healthy pasta made from foxtail millet with tomato sauce",
    price: 200,
    mealType: "dinner",
    category: "Pasta",
    dietaryPreference: "vegetarian",
    ingredients: ["Foxtail Millet Pasta", "Tomatoes", "Basil", "Garlic", "Olive Oil"],
    nutritionalInfo: { calories: 290, protein: 9, carbs: 52, fat: 7, fiber: 7 },
    popular: true,
    spiceLevel: 2,
    preparationTime: 25
  },
  // Additional 18 meals to complete the 38 total
  {
    id: 21,
    name: "Kodo Millet Pancakes",
    description: "Fluffy pancakes made with kodo millet flour and served with maple syrup",
    price: 160,
    mealType: "breakfast",
    category: "Breakfast",
    dietaryPreference: "vegetarian",
    ingredients: ["Kodo Millet Flour", "Eggs", "Milk", "Maple Syrup", "Vanilla"],
    nutritionalInfo: { calories: 280, protein: 9, carbs: 42, fat: 9, fiber: 5 },
    popular: false,
    spiceLevel: 0,
    preparationTime: 18
  },
  {
    id: 22,
    name: "Proso Millet Porridge Bowl",
    description: "Creamy porridge bowl with proso millet, fruits, and nuts",
    price: 140,
    mealType: "breakfast",
    category: "Porridge",
    dietaryPreference: "vegetarian",
    ingredients: ["Proso Millet", "Mixed Berries", "Walnuts", "Chia Seeds", "Coconut Milk"],
    nutritionalInfo: { calories: 260, protein: 8, carbs: 40, fat: 8, fiber: 7 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 15
  },
  {
    id: 23,
    name: "Barnyard Millet Burger",
    description: "Healthy burger patty made from barnyard millet and beans",
    price: 180,
    mealType: "lunch",
    category: "Burgers",
    dietaryPreference: "vegetarian",
    ingredients: ["Barnyard Millet", "Black Beans", "Onions", "Spices", "Whole Wheat Bun"],
    nutritionalInfo: { calories: 320, protein: 14, carbs: 50, fat: 8, fiber: 9 },
    popular: true,
    spiceLevel: 2,
    preparationTime: 25
  },
  {
    id: 24,
    name: "Little Millet Stuffed Paratha",
    description: "Wholesome paratha stuffed with spiced little millet filling",
    price: 130,
    mealType: "lunch",
    category: "Bread",
    dietaryPreference: "vegetarian",
    ingredients: ["Little Millet", "Wheat Flour", "Potatoes", "Green Chilies", "Coriander"],
    nutritionalInfo: { calories: 270, protein: 8, carbs: 45, fat: 7, fiber: 6 },
    popular: false,
    spiceLevel: 3,
    preparationTime: 35
  },
  {
    id: 25,
    name: "Pearl Millet Energy Balls",
    description: "Nutritious energy balls made with pearl millet and dates",
    price: 80,
    mealType: "dinner",
    category: "Snacks",
    dietaryPreference: "vegetarian",
    ingredients: ["Pearl Millet Flour", "Dates", "Almonds", "Coconut", "Sesame Seeds"],
    nutritionalInfo: { calories: 150, protein: 5, carbs: 22, fat: 6, fiber: 4 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 15
  },
  {
    id: 26,
    name: "Finger Millet Noodles",
    description: "Healthy noodles made from finger millet with vegetables",
    price: 170,
    mealType: "dinner",
    category: "Noodles",
    dietaryPreference: "vegetarian",
    ingredients: ["Finger Millet Noodles", "Cabbage", "Carrots", "Soy Sauce", "Sesame Oil"],
    nutritionalInfo: { calories: 240, protein: 8, carbs: 40, fat: 6, fiber: 6 },
    popular: false,
    spiceLevel: 2,
    preparationTime: 20
  },
  {
    id: 27,
    name: "Foxtail Millet Wrap",
    description: "Healthy wrap with foxtail millet patty and fresh vegetables",
    price: 160,
    mealType: "lunch",
    category: "Wraps",
    dietaryPreference: "vegetarian",
    ingredients: ["Foxtail Millet", "Whole Wheat Tortilla", "Lettuce", "Tomatoes", "Hummus"],
    nutritionalInfo: { calories: 290, protein: 10, carbs: 48, fat: 7, fiber: 8 },
    popular: true,
    spiceLevel: 1,
    preparationTime: 15
  },
  {
    id: 28,
    name: "Kodo Millet Kheer",
    description: "Traditional sweet kheer made with kodo millet and milk",
    price: 110,
    mealType: "dinner",
    category: "Dessert",
    dietaryPreference: "vegetarian",
    ingredients: ["Kodo Millet", "Milk", "Sugar", "Cardamom", "Pistachios"],
    nutritionalInfo: { calories: 200, protein: 7, carbs: 32, fat: 6, fiber: 3 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 40
  },
  {
    id: 29,
    name: "Proso Millet Sushi Bowl",
    description: "Fusion sushi bowl with proso millet, avocado, and vegetables",
    price: 220,
    mealType: "lunch",
    category: "Bowls",
    dietaryPreference: "vegetarian",
    ingredients: ["Proso Millet", "Avocado", "Cucumber", "Nori", "Pickled Ginger"],
    nutritionalInfo: { calories: 310, protein: 9, carbs: 50, fat: 9, fiber: 7 },
    popular: false,
    spiceLevel: 1,
    preparationTime: 25
  },
  {
    id: 30,
    name: "Barnyard Millet Muffins",
    description: "Healthy muffins made with barnyard millet flour and blueberries",
    price: 90,
    mealType: "breakfast",
    category: "Baked Goods",
    dietaryPreference: "vegetarian",
    ingredients: ["Barnyard Millet Flour", "Blueberries", "Honey", "Eggs", "Baking Soda"],
    nutritionalInfo: { calories: 180, protein: 6, carbs: 28, fat: 6, fiber: 4 },
    popular: false,
    spiceLevel: 0,
    preparationTime: 30
  },
  {
    id: 31,
    name: "Little Millet Tabbouleh",
    description: "Mediterranean-style salad with little millet, herbs, and lemon",
    price: 150,
    mealType: "lunch",
    category: "Salad",
    dietaryPreference: "vegetarian",
    ingredients: ["Little Millet", "Parsley", "Mint", "Tomatoes", "Lemon Juice"],
    nutritionalInfo: { calories: 190, protein: 6, carbs: 32, fat: 5, fiber: 6 },
    popular: false,
    spiceLevel: 1,
    preparationTime: 20
  },
  {
    id: 32,
    name: "Pearl Millet Pizza Base",
    description: "Healthy pizza with pearl millet base and vegetable toppings",
    price: 250,
    mealType: "dinner",
    category: "Pizza",
    dietaryPreference: "vegetarian",
    ingredients: ["Pearl Millet Flour", "Tomato Sauce", "Mozzarella", "Bell Peppers", "Olives"],
    nutritionalInfo: { calories: 380, protein: 15, carbs: 52, fat: 12, fiber: 7 },
    popular: true,
    spiceLevel: 2,
    preparationTime: 35
  },
  {
    id: 33,
    name: "Finger Millet Granola",
    description: "Crunchy granola made with finger millet, nuts, and dried fruits",
    price: 130,
    mealType: "breakfast",
    category: "Cereals",
    dietaryPreference: "vegetarian",
    ingredients: ["Finger Millet Flakes", "Oats", "Honey", "Mixed Nuts", "Dried Fruits"],
    nutritionalInfo: { calories: 270, protein: 8, carbs: 38, fat: 10, fiber: 6 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 45
  },
  {
    id: 34,
    name: "Foxtail Millet Stuffed Bell Peppers",
    description: "Bell peppers stuffed with spiced foxtail millet and vegetables",
    price: 180,
    mealType: "dinner",
    category: "Stuffed Vegetables",
    dietaryPreference: "vegetarian",
    ingredients: ["Foxtail Millet", "Bell Peppers", "Onions", "Mushrooms", "Cheese"],
    nutritionalInfo: { calories: 260, protein: 10, carbs: 35, fat: 9, fiber: 7 },
    popular: false,
    spiceLevel: 2,
    preparationTime: 40
  },
  {
    id: 35,
    name: "Kodo Millet Ice Cream",
    description: "Creamy ice cream made with kodo millet and vanilla",
    price: 120,
    mealType: "dinner",
    category: "Dessert",
    dietaryPreference: "vegetarian",
    ingredients: ["Kodo Millet", "Cream", "Milk", "Vanilla", "Sugar"],
    nutritionalInfo: { calories: 220, protein: 5, carbs: 28, fat: 10, fiber: 2 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 60
  },
  {
    id: 36,
    name: "Proso Millet Spring Rolls",
    description: "Fresh spring rolls with proso millet noodles and vegetables",
    price: 140,
    mealType: "lunch",
    category: "Rolls",
    dietaryPreference: "vegetarian",
    ingredients: ["Proso Millet Noodles", "Rice Paper", "Lettuce", "Mint", "Peanut Sauce"],
    nutritionalInfo: { calories: 200, protein: 7, carbs: 35, fat: 5, fiber: 5 },
    popular: false,
    spiceLevel: 1,
    preparationTime: 25
  },
  {
    id: 37,
    name: "Barnyard Millet Cheesecake",
    description: "Healthy cheesecake with barnyard millet crust and cream cheese",
    price: 180,
    mealType: "dinner",
    category: "Dessert",
    dietaryPreference: "vegetarian",
    ingredients: ["Barnyard Millet", "Cream Cheese", "Yogurt", "Honey", "Berries"],
    nutritionalInfo: { calories: 290, protein: 8, carbs: 32, fat: 15, fiber: 4 },
    popular: true,
    spiceLevel: 0,
    preparationTime: 90
  },
  {
    id: 38,
    name: "Multi-Millet Power Bowl",
    description: "Nutritious bowl combining all five millets with vegetables and protein",
    price: 280,
    mealType: "lunch",
    category: "Power Bowls",
    dietaryPreference: "vegetarian",
    ingredients: ["Five Millets Mix", "Quinoa", "Avocado", "Chickpeas", "Tahini Dressing"],
    nutritionalInfo: { calories: 420, protein: 18, carbs: 58, fat: 14, fiber: 12 },
    popular: true,
    spiceLevel: 2,
    preparationTime: 30
  }
];