import { InsertMeal } from "@shared/schema";

// Millet menu items
export const milletMeals: InsertMeal[] = [
  // Finger Millet (Ragi) dishes
  {
    name: "Ragi Mudde",
    description: "Traditional finger millet balls served with flavorful curry, rich in calcium and protein.",
    price: 18000, // ₹180
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47",
    calories: 320,
    protein: 14,
    carbs: 40,
    fat: 7,
    fiber: 12,
    sugar: 4,
    mealType: "dinner",
    isPopular: true,
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
    category: "Finger Millet",
  },
  {
    name: "Ragi Roti",
    description: "Nutritious finger millet flatbread served with traditional accompaniments.",
    price: 16000, // ₹160
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40",
    calories: 290,
    protein: 13,
    carbs: 38,
    fat: 6,
    fiber: 10,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Ragi Upma",
    description: "Savory finger millet breakfast dish with vegetables and spices.",
    price: 15000, // ₹150
    imageUrl: "https://images.unsplash.com/photo-1631292784641-43e566b5a352",
    calories: 280,
    protein: 12,
    carbs: 42,
    fat: 6,
    fiber: 8,
    sugar: 3,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  
  // Jowar (Sorghum) dishes
  {
    name: "Jonna Roti",
    description: "Sorghum flatbread served with a protein-rich curry and vegetable side.",
    price: 16000, // ₹160
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40",
    calories: 290,
    protein: 16,
    carbs: 38,
    fat: 5,
    fiber: 11,
    sugar: 2,
    mealType: "dinner",
    isPopular: true,
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Jonna Upma",
    description: "Healthy sorghum breakfast with mixed vegetables and aromatic spices.",
    price: 15500, // ₹155
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 275,
    protein: 13,
    carbs: 38,
    fat: 6,
    fiber: 9,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Jonna Khichdi",
    description: "One-pot sorghum and lentil meal with vegetables and cumin.",
    price: 17000, // ₹170
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 310,
    protein: 15,
    carbs: 44,
    fat: 6,
    fiber: 10,
    sugar: 3,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  
  // Pearl Millet (Sajjalu) dishes
  {
    name: "Sajjalu Roti",
    description: "Pearl millet flatbread, a nutritious alternative to wheat bread.",
    price: 16000, // ₹160
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40",
    calories: 285,
    protein: 15,
    carbs: 37,
    fat: 5,
    fiber: 10,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Sajjalu Khichdi",
    description: "Wholesome pearl millet and lentil dish with vegetables and mild spices.",
    price: 17000, // ₹170
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 305,
    protein: 16,
    carbs: 42,
    fat: 6,
    fiber: 11,
    sugar: 3,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Sajjalu Thalipeeth",
    description: "Multi-grain pearl millet savory pancake with herbs and spices.",
    price: 18000, // ₹180
    imageUrl: "https://images.unsplash.com/photo-1631292784641-43e566b5a352",
    calories: 290,
    protein: 14,
    carbs: 40,
    fat: 7,
    fiber: 9,
    sugar: 2,
    mealType: "breakfast",
    isNew: true,
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Sajjalu Upma",
    description: "Fluffy, spiced pearl millet breakfast dish with cashews and vegetables.",
    price: 15500, // ₹155
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 270,
    protein: 13,
    carbs: 37,
    fat: 7,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: ["tree-nuts"],
  },
  
  // Foxtail Millet (Korralu) dishes
  {
    name: "Korra Pongal",
    description: "Savory foxtail millet porridge with black pepper, cumin, and cashews.",
    price: 17000, // ₹170
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 275,
    protein: 13,
    carbs: 38,
    fat: 8,
    fiber: 9,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: ["tree-nuts"],
  },
  {
    name: "Korra Upma",
    description: "Spiced foxtail millet breakfast with seasonal vegetables and curry leaves.",
    price: 15500, // ₹155
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 265,
    protein: 12,
    carbs: 36,
    fat: 6,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Korra Biryani",
    description: "Traditional Hyderabadi biryani made with foxtail millet, aromatic spices, and seasonal vegetables.",
    price: 22000, // ₹220
    imageUrl: "https://images.unsplash.com/photo-1624291649578-5a1580e7426c",
    calories: 350,
    protein: 15,
    carbs: 45,
    fat: 8,
    fiber: 10,
    sugar: 2,
    mealType: "lunch",
    isPopular: true,
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Korra Fried Rice",
    description: "Stir-fried foxtail millet with mixed vegetables and Oriental flavors.",
    price: 19000, // ₹190
    imageUrl: "https://images.unsplash.com/photo-1624291649578-5a1580e7426c",
    calories: 315,
    protein: 13,
    carbs: 42,
    fat: 9,
    fiber: 8,
    sugar: 3,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: ["soy"],
  },
  
  // Little Millet (Samalu) dishes
  {
    name: "Little Millet Pulao",
    description: "Fragrant little millet cooked with mixed vegetables and mild spices.",
    price: 18500, // ₹185
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 310,
    protein: 12,
    carbs: 42,
    fat: 7,
    fiber: 9,
    sugar: 3,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Little Millet Dosa",
    description: "Crispy South Indian crepe made with fermented little millet batter, served with chutney.",
    price: 18000, // ₹180
    imageUrl: "https://images.unsplash.com/photo-1631292784641-43e566b5a352",
    calories: 280,
    protein: 12,
    carbs: 42,
    fat: 6,
    fiber: 8,
    sugar: 3,
    mealType: "breakfast",
    isPopular: true,
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Little Millet Upma",
    description: "Savory breakfast made with little millet, vegetables, and tempering spices.",
    price: 15500, // ₹155
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 260,
    protein: 11,
    carbs: 38,
    fat: 6,
    fiber: 7,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Little Millet Khichdi",
    description: "Comforting one-pot meal with little millet, lentils, and mixed vegetables.",
    price: 17500, // ₹175
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 295,
    protein: 14,
    carbs: 40,
    fat: 7,
    fiber: 9,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  
  // Proso Millet dishes
  {
    name: "Proso Millet Dosa",
    description: "Thin, crispy crepe made with fermented proso millet batter, served with sambar and chutney.",
    price: 18000, // ₹180
    imageUrl: "https://images.unsplash.com/photo-1631292784641-43e566b5a352",
    calories: 275,
    protein: 12,
    carbs: 40,
    fat: 6,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Proso Millet Khichdi",
    description: "Hearty and nutritious one-pot meal with proso millet, lentils, and vegetables.",
    price: 17500, // ₹175
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 300,
    protein: 15,
    carbs: 41,
    fat: 7,
    fiber: 9,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Proso Millet Upma",
    description: "Savory breakfast preparation with proso millet, vegetables, and traditional tempering.",
    price: 15500, // ₹155
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 270,
    protein: 12,
    carbs: 39,
    fat: 6,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Proso Millet Biryani",
    description: "Flavorful proso millet with aromatic spices, vegetables, and fragrant herbs.",
    price: 22000, // ₹220
    imageUrl: "https://images.unsplash.com/photo-1624291649578-5a1580e7426c",
    calories: 340,
    protein: 15,
    carbs: 44,
    fat: 8,
    fiber: 10,
    sugar: 3,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  
  // Barnyard Millet (Udalu) dishes
  {
    name: "Barnyard Millet Khichdi",
    description: "Simple, nutritious one-pot barnyard millet and lentil preparation.",
    price: 17000, // ₹170
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 290,
    protein: 14,
    carbs: 40,
    fat: 6,
    fiber: 9,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Barnyard Millet Upma",
    description: "Healthy South Indian breakfast made with barnyard millet and vegetables.",
    price: 15500, // ₹155
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 265,
    protein: 12,
    carbs: 38,
    fat: 6,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Barnyard Millet Pulao",
    description: "Fragrant barnyard millet cooked with vegetables and mild spices.",
    price: 18500, // ₹185
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 305,
    protein: 13,
    carbs: 42,
    fat: 7,
    fiber: 9,
    sugar: 2,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  
  // Kodo Millet (Arikelu) dishes
  {
    name: "Kodo Millet Upma",
    description: "Light and nutritious breakfast made with kodo millet, vegetables, and spices.",
    price: 15000, // ₹150
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 260,
    protein: 11,
    carbs: 37,
    fat: 6,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Kodo Millet Biryani",
    description: "Fragrant kodo millet cooked with vegetables and aromatic spices.",
    price: 22000, // ₹220
    imageUrl: "https://images.unsplash.com/photo-1624291649578-5a1580e7426c",
    calories: 335,
    protein: 14,
    carbs: 43,
    fat: 8,
    fiber: 9,
    sugar: 3,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: [],
  },
  {
    name: "Kodo Millet Porridge",
    description: "Comforting breakfast porridge made with kodo millet, milk, and fruits.",
    price: 14000, // ₹140
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b",
    calories: 270,
    protein: 10,
    carbs: 40,
    fat: 8,
    fiber: 7,
    sugar: 12,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian"],
    allergens: ["milk"],
  },
  {
    name: "Kodo Millet Khichdi",
    description: "Wholesome kodo millet and lentil dish with vegetables and ghee.",
    price: 17000, // ₹170
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 295,
    protein: 14,
    carbs: 40,
    fat: 7,
    fiber: 9,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: ["milk"],
  },
  
  // Quinoa dishes
  {
    name: "Quinoa Pulao",
    description: "Flavorful quinoa cooked with mixed vegetables and aromatic spices.",
    price: 21000, // ₹210
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 315,
    protein: 16,
    carbs: 42,
    fat: 8,
    fiber: 10,
    sugar: 3,
    mealType: "lunch",
    isNew: true,
    dietaryPreferences: ["vegetarian", "high-protein", "gluten-free"],
    allergens: [],
  },
  {
    name: "Quinoa Stir-fry",
    description: "Healthy quinoa stir-fried with mixed vegetables and soy sauce.",
    price: 19000, // ₹190
    imageUrl: "https://images.unsplash.com/photo-1624291649578-5a1580e7426c",
    calories: 320,
    protein: 15,
    carbs: 43,
    fat: 9,
    fiber: 9,
    sugar: 4,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "high-protein"],
    allergens: ["soy"],
  },
  {
    name: "Quinoa Upma",
    description: "South Indian-style quinoa breakfast with vegetables and tempering.",
    price: 16000, // ₹160
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 280,
    protein: 13,
    carbs: 39,
    fat: 7,
    fiber: 8,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  
  // Amaranth dishes
  {
    name: "Rajgira Ladoo",
    description: "Sweet amaranth balls with ghee, jaggery, and nuts - a nutritious dessert.",
    price: 15000, // ₹150
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b",
    calories: 280,
    protein: 9,
    carbs: 42,
    fat: 10,
    fiber: 6,
    sugar: 20,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: ["tree-nuts", "milk"],
  },
  {
    name: "Amaranth Paratha",
    description: "Stuffed flatbread made with amaranth flour and spiced potato filling.",
    price: 16000, // ₹160
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40",
    calories: 295,
    protein: 12,
    carbs: 40,
    fat: 8,
    fiber: 7,
    sugar: 2,
    mealType: "breakfast",
    dietaryPreferences: ["vegetarian"],
    allergens: [],
  },
  {
    name: "Amaranth Stir-fry",
    description: "Nutritious amaranth greens stir-fried with spices and onions.",
    price: 17000, // ₹170
    imageUrl: "https://images.unsplash.com/photo-1624291649578-5a1580e7426c",
    calories: 260,
    protein: 14,
    carbs: 35,
    fat: 7,
    fiber: 10,
    sugar: 3,
    mealType: "lunch",
    dietaryPreferences: ["vegetarian", "gluten-free", "high-protein"],
    allergens: [],
  },
  
  // Buckwheat dishes
  {
    name: "Buckwheat Roti",
    description: "Gluten-free flatbread made with buckwheat flour, served with curry.",
    price: 16000, // ₹160
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40",
    calories: 285,
    protein: 13,
    carbs: 38,
    fat: 6,
    fiber: 9,
    sugar: 2,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: [],
  },
  {
    name: "Buckwheat Khichdi",
    description: "Nutritious one-pot meal with buckwheat, lentils, and vegetables.",
    price: 17500, // ₹175
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107aa3c107",
    calories: 300,
    protein: 15,
    carbs: 41,
    fat: 7,
    fiber: 10,
    sugar: 3,
    mealType: "dinner",
    dietaryPreferences: ["vegetarian", "gluten-free", "high-protein"],
    allergens: [],
  },
  
  // Wild Rice dish
  {
    name: "Wild Rice Soup",
    description: "Creamy and hearty wild rice soup with vegetables and herbs.",
    price: 19000, // ₹190
    imageUrl: "https://images.unsplash.com/photo-1553531889-56cc480ac5cb",
    calories: 320,
    protein: 12,
    carbs: 43,
    fat: 10,
    fiber: 8,
    sugar: 4,
    mealType: "dinner",
    isNew: true,
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergens: ["milk"],
  }
];